### ISSUE TITLE
Can't select multiple images in "Add new book" section

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Website#102]
In seller panel, **Add new book** section.

There is no option to add more images after selecting one image, if we click on that image again to add more new images, it replaces previously selected images.
The only way to add multiple images is to select all required images at once.

It would be better if we have a button named **Add more images** or a plus icon to add more images.
![book img](https://user-images.githubusercontent.com/55583961/136605245-388b37bd-ec08-4556-a409-775bb58fb79e.png)

![book multiple img](https://user-images.githubusercontent.com/55583961/136605546-7e717c8f-115e-4a32-9154-32dd959089b7.png)

**Comment by benardcharumbira** [comment]
@RohitKumar-200 may you please assign this to me

**Comment by RohitKumar-200** [comment]
Thank you for your contribution @benardcharumbira
