### ISSUE TITLE
UI changes required for deleted books

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Website#103]
Books which are deleted by their seller are still accessible through URL (Through bookmarks or something else). It has the same UI as of normally available book.

Current UI for the deleted book:
![Screenshot (392)](https://user-images.githubusercontent.com/55583961/136623408-e0df3e85-e066-4045-b205-e3b8bd48ba24.png)

For a deleted book, a red-colored note should appear that the book is not available and buttons on its page should be disabled.
Something like this pic.
![Final design](https://user-images.githubusercontent.com/55583961/136623442-1a0814f5-327e-42b6-b1f5-7905b0f49af2.png)

To check if a book is deleted or not. API response of book details will contain "status" as "Deleted" for a deleted book.

For testing purposes, you can use this book Id of a deleted book: [**6100f8306f06920022e111f9**](https://bookshlf.web.app/BookDetails/6100f8306f06920022e111f9)  
or you can add a new book and then delete it to replicate this issue.

**Comment by taimooralqureshi** [comment]
please assign this task to me!

**Comment by taimooralqureshi** [comment]
[@RohitKumar-200,](url) please look into it > [PR#105](https://github.com/Bookshlf-in/Website/pull/105)
