### ISSUE TITLE
Stop User From Buy Now if Not Logged In!

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#110]
![Screenshot 2021-10-11 192027](https://user-images.githubusercontent.com/56078689/136801570-8cd86db9-0c8e-49ad-a675-fd70d5fce149.png)

- If User Is not Logged In The Buy Now should Not redirect it to payments page.
- Currently Even IF user is not Logged In it redirects to Payments page which is Wrong.
- A simple alert can be shown to login to purchase the book.(use Material UI alert Component)
- To Know if User is Logged In or Not use `UserContext` or Observe in `navbar` etc components to get better Idea.

**Comment by RohitKumar-200** [comment]
Issues are assigned on the basis of **first come first serve**. So I have assigned it to @logicalahara

**Comment by MohsinNajmuddin** [comment]
@Mrhb787 this one is now assigned to me?

**Comment by MohsinNajmuddin** [comment]
@Mrhb787 ok

**Comment by MohsinNajmuddin** [comment]
@Mrhb787 Raised the PR. Please review. I have updated the message to look it more appropriate.
