### ISSUE TITLE
Add New Address Option in Payment Not Working.

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#111]
![Screenshot 2021-10-11 192848](https://user-images.githubusercontent.com/56078689/136802804-71bae964-ae97-49dc-8bd1-79fffc67f81f.png)

- The `Add Address` Option with ```value = addNew ``` when selected should redirect user to `/UserProfile/4` to add new address but currently it does not redirects to no where.
- 'useHistory' hook can be used to solve the problem.

### Should be done like this..

```
if (Option-Value === "addNew") {
                history.push("/UserProfile/4");
              } else {
                // other work
              }
```

**Comment by mtwn105** [comment]
Hi @Mrhb787 can I try this?

**Comment by mtwn105** [comment]
Added PR #116
