### ISSUE TITLE
Image Magnifier Glass Needed In Book Details Component

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#114]
![Screenshot 2021-10-12 132310](https://user-images.githubusercontent.com/56078689/136915055-37dd88ff-f197-4d61-b9da-cd19f55d5448.png)

- It would be really great if user can magnify on hover over image to get all details.
- An Image Magnifier Glass will be Great.
- Refer This to Know how to make It work : [How To Create an Image Magnifier](https://www.w3schools.com/howto/howto_js_image_magnifier_glass.asp)

**Comment by Mrhb787** [comment]
Issue is unassigned and Open for contribution.

**Comment by yash-jain24** [comment]
I want to try can you assign this to me?

**Comment by yash-jain24** [comment]
![image](https://user-images.githubusercontent.com/60182679/141504898-e391fb3b-e47c-4216-9699-73165c4c050d.png)
I have implemented it is it okay?

**Comment by yash-jain24** [comment]
I made a pull request , review it.

**Comment by Mrhb787** [comment]
Issue Resolved
