### ISSUE TITLE
Add Reviews Component Not Mobile Friendly

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#115]
![Screenshot 2021-10-12 142734](https://user-images.githubusercontent.com/56078689/136925455-2e45eda9-0dd1-45c9-8078-8d918dc1b6f1.png)
![Screenshot 2021-10-12 142836](https://user-images.githubusercontent.com/56078689/136925468-f0449da3-6141-419f-8b92-89d078a1eb20.png)

- To Open this Component go to this Route : `AddReview/60f5594a8d80580022865f22`
- The Component isn't Mobile Friendly and breaks in small screens, Use media Queries to solve this issue.
- Also Some UI Enhancements are Required. (CSS improvements)
- Component is Located in `src/components/AddReviews`

**Comment by MohsinNajmuddin** [comment]
@Mrhb787 I can do this. Assign it to me

**Comment by Mrhb787** [comment]
@MohsinNajmuddin any Updates ?
