### ISSUE TITLE
Navbar Small Popup Menu has a wrong route to seller Panel

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#118]
![Screenshot 2021-10-12 204642](https://user-images.githubusercontent.com/56078689/136983405-b21aaee9-7bf9-4feb-ae02-90e0e6d9f525.png)

- #### When we Click on `Sell Books` we get redirected to `/SellerPanel` but we should be redirected to `/SellerPanel/4`. 
- #### Popup Menu is located in Navbar component `src/components/Navbar/Navbar.js`

**Comment by Mrhb787** [comment]
@yash-jain24 I have assigned this issue to you now.

**Comment by yash-jain24** [comment]
![image](https://user-images.githubusercontent.com/60182679/136997318-c692934f-95f5-42b7-adb1-a69dcea1093d.png)
in my local environment sellerpanel is not working
