### ISSUE TITLE
Update the styling of Reviews section

### ISSUE THREAD

**Issue by rockingrohit9639** [Bookshlf-in/Website#143]
Hey there, 
I would like to update the styling of the reviews section.

Currently, we have this ⬇️ 
![image](https://user-images.githubusercontent.com/40729749/137248878-475560b8-dfdc-442f-8f33-cc41114f3b01.png)

I would like to update this like this ⬇️ 
![image](https://user-images.githubusercontent.com/40729749/137250136-b290f0dd-7504-44cf-aa30-c9610652158b.png)

Can I work on this?

**Comment by RohitKumar-200** [comment]
It looks pretty good. What are your thoughts @Mrhb787

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Assigned you

Thank you.
