### ISSUE TITLE
Seller Public Profile CSS Enhancements

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#155]
### Current 
![1](https://user-images.githubusercontent.com/56078689/137545956-aad6ac25-fc59-4385-b2f7-a0621a98b722.png)

### Sample Improvement
![2](https://user-images.githubusercontent.com/56078689/137545072-23976273-c810-4ebb-ab70-b305f325dbf7.png)

- Refer UserProfile by creating account and going to **UserPanel** or Register as Seller and analyze the `SellerPanel.css`

**Comment by wali39** [comment]
already designed 
so why you assign me ? you need close it
![cc](https://user-images.githubusercontent.com/57776479/137578610-0b2ce109-1249-4895-9672-b17b6b7e11fd.PNG)

**Comment by Mrhb787** [comment]
@wali39 fetch your code from dev branch, run it locally, and then go to this route [http://localhost:3000/SellerProfile/60f09b1a3a24d10022919697](http://localhost:3000/SellerProfile/60f09b1a3a24d10022919697)

This component don't have any css file. Create a new css file and add stylings in it.

![image](https://user-images.githubusercontent.com/56078689/137582816-cf2106bb-dd14-4c56-b6da-bc7039612b53.png)
