### ISSUE TITLE
There is a small problem for the smallest screen on Profile page:

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#156]
There is a small problem for the smallest screen on Profile page:
avatar covers user's information.
<img width="241" alt="Screenshot 2021-10-15 at 15 21 15" src="https://user-images.githubusercontent.com/65239393/137493861-586b32c8-fe2c-4d1a-add6-bc36715635c7.png">

_Originally posted by @Neniya in https://github.com/Bookshlf-in/Website/issues/140#issuecomment-944299558_

**Comment by codex111** [comment]
can i work on it
