### ISSUE TITLE
Missing Social Media Links in Contact US form.

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#170]
![image](https://user-images.githubusercontent.com/56078689/137919852-e9a75d3a-1dba-4b3c-a251-28fefdc47709.png)

- Get Links From Here : [Bookshlf | Linktree](https://linktr.ee/bookshlf)
- Just use `<Link to={{ pathname = "[Social-Media-Link]", }}> [Text] </Link>` OR refer **About Us** Component.

**Comment by Mrhb787** [comment]
@YashGupta29 Assigned You

**Comment by maazkhalil** [comment]
hi, can you assign this issue to me? I would love to contribute

**Comment by Mrhb787** [comment]
> is there any other related issue I can contribute to?

We are always trying to find out issues and you can star this repo for future references. We are always open to any improvement you can make to our project.
