### ISSUE TITLE
Replace normal tables with Material UI tables for Display of Address list in Profile Panel and Seller Panel

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#191]
![Screenshot](https://user-images.githubusercontent.com/56078689/141646295-7e65ff0f-b42d-436d-8717-10ad135b5780.jpg)

- Currently Normal Tables are present with no better functionalities and UI.
- Material UI Provides Rich UI Tables with different features such as column sorting, better stacking, adaptive tables etc.
- Refer this [Material UI Tables](https://v4.mui.com/components/tables/#table)

### Note
> Material UI is already in package

**Comment by yash-jain24** [comment]
I want to work on this.

**Comment by yash-jain24** [comment]
should I implement it using DataGrid component or basic MUI table?

**Comment by Mrhb787** [comment]
Data grid would be good.

Use this for reference :
https://mui.com/api/data-grid/data-grid/

**Comment by Mrhb787** [comment]
@yash-jain24 any progress

**Comment by yash-jain24** [comment]
Yeah, I am working on it.

**Comment by yash-jain24** [comment]
made a PR, review it.

**Comment by Mrhb787** [comment]
Issue Resolved Closing it Now
