### ISSUE TITLE
UI Designs For Different Components

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#261]
We Would Love to have Interactive, Fluid, and Lucrative designs for our platform.
There are a lot of components such as `Login`, `SignUp`, `AboutUs`, and `ContactUs` etc.
Remember to Make the designs in `Figma` and also that they should maintain a constant binary color theme.
> Submit Component Designs Below this Issue Only.

- Refer [Figma](https://www.figma.com/) for more Information
- Also Check Out Preferred Binary Color gave in this [Issue](https://github.com/Bookshlf-in/Website/issues/260)

**Comment by Dhruvil-P** [comment]
Hey there! How's it going? I'd like to take responsibility for this issue.

**Comment by Mrhb787** [comment]
Hi @Dhruvil-P Please go ahead. Assigning this to you.

**Comment by Dhruvil-P** [comment]
Thanks for letting me know. Will start working on it.

**Comment by Dhruvil-P** [comment]
Hey! Can you confirm the components which need to be redesigned in Figma? Thanks.

**Comment by RohitKumar-200** [comment]
Hi @Dhruvil-P You can try starting with [search page](https://bookshlf.in/SearchResult/tag:ALL) [Book details page](https://bookshlf.in/BookDetails/6346ddaa110c6db766eacf5b) [Home page](https://bookshlf.in/) or you can choose any other page present in website you want to re-design.

**Comment by Dhruvil-P** [comment]
Perfect. 👍🏻

**Comment by Dhruvil-P** [comment]
Hey! The designs are done. How should I proceed?

**Comment by Dhruvil-P** [comment]
Hey @RohitKumar-200. I created a PR for the designs. Here's a quick look if wanna review it. And, lemme know what other design tasks I need to do.
![Desktop - 3](https://user-images.githubusercontent.com/76477111/197686902-9adb59ee-416a-4d34-8596-eb18245ad85d.png)
![Desktop - 4](https://user-images.githubusercontent.com/76477111/197686910-de312eda-7901-45cf-827c-78ddcfbb2897.png)
![Desktop - 5](https://user-images.githubusercontent.com/76477111/197686913-bf697aff-f651-43ab-8f5a-2819f6dfc96f.png)

**Comment by RohitKumar-200** [comment]
Hi @Dhruvil-P 

I am sorry, I couldn't reply to you as I was little busy.

I reviewed your pull request #275 
Since you are adding figma link directly, you can add the link in [readme.md](https://github.com/Bookshlf-in/Website/blob/main/README.md) itself

For reference, here is a screenshot, you can put all your links just above future plan heading:
![image](https://user-images.githubusercontent.com/55583961/198087788-2819d4be-2dc0-4c8e-b917-f7917a8d71e9.png)


You can create different pages in same figma file (You can see this in the top left corner), so attach different links for different pages:
![image](https://user-images.githubusercontent.com/55583961/198087985-8c66d8a4-1d8b-4f47-98be-cd581dff6a20.png)

So, please add the design page in this manner (In readme.md), you can either add all pages at once, or create separate pull requests for different page designs.

If you have any queries, feel free to ask. This time, I will try to reply faster 🙃

**Comment by RohitKumar-200** [comment]
By the way, your designs are really great!! 

Thanks for your contribution @Dhruvil-P  🙌

**Comment by Mrhb787** [comment]
Great Work @Dhruvil-P 🙌

**Comment by Dhruvil-P** [comment]
> Hi @Dhruvil-P
> 
> I am sorry, I couldn't reply to you as I was little busy.
> 
> I reviewed your pull request #275 Since you are adding figma link directly, you can add the link in [readme.md](https://github.com/Bookshlf-in/Website/blob/main/README.md) itself
> 
> For reference, here is a screenshot, you can put all your links just above future plan heading: ![image](https://user-images.githubusercontent.com/55583961/198087788-2819d4be-2dc0-4c8e-b917-f7917a8d71e9.png)
> 
> You can create different pages in same figma file (You can see this in the top left corner), so attach different links for different pages: ![image](https://user-images.githubusercontent.com/55583961/198087985-8c66d8a4-1d8b-4f47-98be-cd581dff6a20.png)
> 
> So, please add the design page in this manner (In readme.md), you can either add all pages at once, or create separate pull requests for different page designs.
> 
> If you have any queries, feel free to ask. This time, I will try to reply faster 🙃

`

> Hi @Dhruvil-P
> 
> I am sorry, I couldn't reply to you as I was little busy.
> 
> I reviewed your pull request #275 Since you are adding figma link directly, you can add the link in [readme.md](https://github.com/Bookshlf-in/Website/blob/main/README.md) itself
> 
> For reference, here is a screenshot, you can put all your links just above future plan heading: ![image](https://user-images.githubusercontent.com/55583961/198087788-2819d4be-2dc0-4c8e-b917-f7917a8d71e9.png)
> 
> You can create different pages in same figma file (You can see this in the top left corner), so attach different links for different pages: ![image](https://user-images.githubusercontent.com/55583961/198087985-8c66d8a4-1d8b-4f47-98be-cd581dff6a20.png)
> 
> So, please add the design page in this manner (In readme.md), you can either add all pages at once, or create separate pull requests for different page designs.
> 
> If you have any queries, feel free to ask. This time, I will try to reply faster 🙃

Understood. I'll create PRs for separate Figma pages.

**Comment by Dhruvil-P** [comment]
Thanks, guys. Glad ya'll like it.

**Comment by Mrhb787** [comment]
Issue is resolved.
Closing it now.
