### ISSUE TITLE
Remove Unverified Status from Seller Profile.

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#268]
- If seller is unverified don't show `unverified` tag meaning only show verified tag when seller is verified.

**Comment by bkjain655** [comment]
Hi @Mrhb787 ,

I can work on this issue.  please assign it to me.
Just clarifying the issue that we don't want to show unverified tag in the detail page if the seller is unverified.

**Comment by Mrhb787** [comment]
@bkjain655 Assigned You.

**Comment by bkjain655** [comment]
Hi @Mrhb787 ,

Can you share login details, I have made the changes but wanted to test it once & your readme or env isn't sharing any such details?
Else I can raise a PR & you can validate it & approve it (if everything is fine).

Thank you,
Bhavesh.

**Comment by bkjain655** [comment]
@Mrhb787 : Validated & raised a PR (https://github.com/Bookshlf-in/Website/pull/269). Please check it.

**Comment by Mrhb787** [comment]
Solved in #269.

Closing this issue.
