### ISSUE TITLE
Cart Purchase Qnty Update API Issue

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#49]
- After Increasing the Purchase Qnty if we reload the instance is lost.

**Comment by gyen92** [comment]
I want to take this issue if you don't mind.

**Comment by Mrhb787** [comment]
> I want to take this issue if you don't mind.

**Yes go for it!**
- After Fixing the issue Send the PR to Dev Branch only.

- Issue (explaining again)
> if we increase the items quantity in cart it only gets updated in frontend not in the server(backend). so is we reload before going to checkout the changes get dissolved. Use Axios for API and do not modify or change any other component otherwise the PR will be rejected.

**Comment by Mrhb787** [comment]
Issue Has Been Solved I will close this Now

**Comment by AngelicHeaven** [comment]
Alright, so I can work on this, right?

**Comment by Mrhb787** [comment]
> Alright, so I can work on this, right?

Yeah Go For It

**Comment by Mrhb787** [comment]
@AngelicHeaven Are You Working on this Issue ?

**Comment by AngelicHeaven** [comment]
@Mrhb787 Hi, since I have some issues with remote PR in this moment, I would like to request more time. I will try to send my PR for this issue  during the weekend.

**Comment by AngelicHeaven** [comment]
@Mrhb787  @bhumithakur  Hello, I am sorry for the complication. I have sent the PR for this issue, however now I see I was unassigned from this issue few days ago and there is a new assignee for this.
