### ISSUE TITLE
Website Is Not Mobile Friendly

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#52]
- Website breaks on Small Screens

**Comment by enristra** [comment]
I can handle it!

**Comment by Mrhb787** [comment]
@enristra There Is No Such Specific Breakdowns but you can test all available pages in different screen size and if you find out some breakdowns you are free to work on it.

**Comment by RohitKumar-200** [comment]
I think, now there are no issues regarding responsiveness, so I am closing it.
