### ISSUE TITLE
Sidenav Is not working!

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#53]
- SideNav for small screens lacks functioning
![Annotation 2021-07-22 200731](https://user-images.githubusercontent.com/56078689/126657687-c7e6715a-7989-4f6c-84d8-82d0de43be22.png)

**Comment by VWRoli** [comment]
Hello! I would like to tackle this issue, if I may.

**Comment by Mrhb787** [comment]
**Sure Go For It!**
Remember to
- **Send PR** only to `dev` branch.
- Not change any other Components.

**Issue**
- [ ] Sidenav Lacks Navigation.
- [ ] Lacks Search API Functioning
- [ ] UI Improvements

**Comment by VWRoli** [comment]
I have a question. "Profile" and "Cart" menu has a profile class which only functionality is to show these two menu links under 650px. Which to me seems redundant, considering the sidenav only visible under around 850px.
I personally would delete this part of the code as it doesn't make sense to NOT show these two menu links between 850px and 650px.

Let me know what should I do with it. Or if I missed something.

` {/* hidden until screen size is smaller than 650px */}
        <Link to="" className="Profile">
          <input type="text" style={{width: "150px", height: "40px"}} />
          &nbsp;<i className="fas fa-search"></i>
        </Link>
        <Link to="" className="Profile">
          Profile&nbsp;<i className="fas fa-user-circle"></i>
        </Link>
        <Link className="Profile" to="/Cart">
          Cart&nbsp;<i className="fas fa-shopping-cart"></i>
        </Link>
        {/* ends here */}`

**Comment by Mrhb787** [comment]
> I have a question. "Profile" and "Cart" menu has a profile class which only functionality is to show these two menu links under 650px. Which to me seems redundant, considering the sidenav only visible under around 850px.
> I personally would delete this part of the code as it doesn't make sense to NOT show these two menu links between 850px and 650px.
> 
> Let me know what should I do with it. Or if I missed something.
> 
```
 {/* hidden until screen size is smaller than 650px */} 
 <Link to="" className="Profile"> 
 <input type="text" style={{width: "150px", height: "40px"}} /> &nbsp;<i className="fas fa-search"></i> </Link> 
 <Link to="" className="Profile"> Profile&nbsp;<i className="fas fa-user-circle"></i> </Link> 
 <Link className="Profile" to="/Cart"> Cart&nbsp;<i className="fas fa-shopping-cart"></i> </Link> 
 {/* ends here */}
 ```

- When Screen Size (width) gets `800px` or below **Sidenav** appears with only **Nav-links.** `Cart, Wishlist and Search box` does not appear in **Sidenav** and they stay in the original Navbar but when screen size gets `650px` or below these elements appear in **Sidenav** and gets hidden in main **Navbar**.

_Result of Removing the Above Chunk of Code_
**Sidenav** will not have `Search Box , Cart and Wishlist` in it on screens with width smaller than `650px` and they will also not be present in Main **Nav-Bar** which means we are basically removing these elements for smaller screens.

- I hope you understood why we can't remove that piece of code. Please Let me Know if i didn't understood you correctly and thanks for showing interest and helping.

**Comment by VWRoli** [comment]
I see, I missed that completely. Thanks for the answer. I will proceed accordingly.
