### ISSUE TITLE
Login process improvement

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Website#56]
After login, the user is provided an option to log in as a user, seller, or admin.
I think It is useless to ask it in case a user is not an admin, as selecting user or seller is same, we should redirect him to the home page directly without asking,
If the user is an admin, we should give an option to log in as admin or user.  

![login](https://user-images.githubusercontent.com/55583961/126762498-f2e5e1dc-19a4-4cf1-88a5-3aad2cb7a93e.png)

What are your thoughts on this @Mrhb787

**Comment by Mrhb787** [comment]
I have Fixed all related issues regarding this.
