### ISSUE TITLE
Sitemap Required

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#72]
- Currently there is no Sitemap present.
- A sitemap is a file where you provide information about the pages, videos, and other files on your site, and the relationships between them.
- Create a component as **Sitemap** in `src/components` and create a **Sitemap.js** file as the Sitemap.
- Css can also be added using in Same Directory with same name as **Sitemap.css**.
- Route to Sitemap will be `/Sitemap` but addition of this is optional as i will be adding it regardless of the pr.
> Note : Do Not create any other routes.

**Comment by ansh-saini** [comment]
Hi, I would like to work on this. Can you please assign it to me?

**Comment by Mrhb787** [comment]
@ansh-saini I have assigned this issue to you.
