### ISSUE TITLE
'Enter' Keypress missing in Search bar in Navbar Component 

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#73]
![Annotation 2021-09-20 121007](https://user-images.githubusercontent.com/56078689/133964513-df88ae6d-7005-4195-ac4d-73fcb3a0f667.png)

- After writing a Search query when you press **"Enter Key"** nothing happens. 
- A simple Keypress Event can be added to solve the problem.

**Comment by minhhang107** [comment]
Can I work on this issue?

**Comment by Ujjwal-Gupta-web** [comment]
@Mrhb787 
PR #90 
Resolves this issue

**Comment by minhhang107** [comment]
@RohitKumar-200 I'll take on this one. Thanks
