### ISSUE TITLE
'Enter' Keypress missing in Search bar in Sidenav Component 

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#74]
![Annotation 2021-09-20 121500](https://user-images.githubusercontent.com/56078689/133965289-98612871-51fb-433e-97fc-c81038f082ca.png)
- After writing a Search query when you press "Enter Key" nothing happens.
- A simple Keypress Event can be added to solve the problem.

**Comment by PuneetDabral** [comment]
sir can i do my first contribution here....!!?sir if you can help me

**Comment by RohitKumar-200** [comment]
Go for it!!
We will be happy to have you as a contributor. And feel free to ask any doubt.
😃

**Comment by PuneetDabral** [comment]
ok sir i will try ...

**Comment by Mrhb787** [comment]
> sir can i do my first contribution here....!!?sir if you can help me

- Please Go for it.
- Kindly Note to Follow Contribution guidelines and only send PRs to `dev` branch. PRs sent to other branches will be rejected.

**Comment by PuneetDabral** [comment]
hello sir help me to resolve this issue!! i have done the set up of the  project  after that what i can do ....

**Comment by Mrhb787** [comment]
- If you have successfully installed the project use `npm start` in console to start the website locally. 
- Go to project main Directory then `src/components/Navbar/Sidenav.js`
- Understand the Sidenav react Js written.
- Make changes to search Bar in Sidenav you can simply use Keypress event of js for this.
- A good understanding of react js is required.
- Refer below Image for better Understanding.
![Annotation 2021-09-21 133732](https://user-images.githubusercontent.com/56078689/134135308-61b6d311-467f-4896-94ab-e401bf51e84f.png)

**Comment by PuneetDabral** [comment]
sir i am new in react...

**Comment by Mrhb787** [comment]
Please share the code used. 
- You can drop Screenshot.
- Or written Code

**Comment by PuneetDabral** [comment]
ok i will try please check ...

**Comment by PuneetDabral** [comment]
![Screenshot (90)](https://user-images.githubusercontent.com/86554356/134137213-b705a923-11bd-41bf-bb28-8b1088a19c7d.png)

**Comment by Mrhb787** [comment]
- Keypress is general Event in Javascript But React uses it differently.
- for Reacts the event is `onKeyPress`.
- Try to understand **CODE** below carefully.
```
onKeyPress ={ (event) => {
              if (event.key === "{KEY NAME}")  // Name of the key that is required to be triggered eg : Enter
              {
                event.preventDefault();     // to prevent any default action that is performed by that keyPress
               // Functions() to be performed 
              }
    }}
```
- Hope You will now be able to solve the issue.

**Comment by PuneetDabral** [comment]
i should change KEY NAME to Enter ....

**Comment by Mrhb787** [comment]
> i should change KEY NAME to Enter ....

**YES**
and remember to add search functionality.
for that just redirect to this path.
```
{`/SearchResult/${Search === "" ? "books" : Search}`
```

**Comment by PuneetDabral** [comment]
can you check this ..

**Comment by PuneetDabral** [comment]
can i made a pr

**Comment by Mrhb787** [comment]
> Yes You can

**Comment by MuhammadTanveer94** [comment]
@Mrhb787 @PuneetDabral could you please assign me this? i would love to do this task.

**Comment by RohitKumar-200** [comment]
@MuhammadTanveer94 I have assigned you this task. Feel free to ask any doubt.

**Comment by MuhammadTanveer94** [comment]
@RohitKumar-200 @Mrhb787  please look into this PR https://github.com/Bookshlf-in/Website/pull/87. Kindly merge it.

**Comment by Mrhb787** [comment]
Issue Has Been Resolved I will Close this Issue Now.
