### ISSUE TITLE
"Hide" Profile Link when Not Logged-In in Sidenav Component

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#75]
![Annotation 2021-09-20 121500](https://user-images.githubusercontent.com/56078689/133965601-f90aa01f-e9cf-4bb9-875a-cb5350700169.png)

- When Not Logged-In Profile Link shouldn't be visible as that does not makes any sense.
- A simple ternary operator can be used with checking if user is logged in then show the profile link otherwise hide it.
- More Help can be taken from Sidenav Component itself.

**Comment by AnimeshMore** [comment]
Hello, I would like to work on this issue.

**Comment by Mrhb787** [comment]
Sure Go For It!
