### ISSUE TITLE
Display of items count in cart in SideNav

### ISSUE THREAD

**Issue by Mrhb787** [Bookshlf-in/Website#80]
- It will be really good if Cart In **SideNav** Also display cart items count.
- for example
![Annotation 2021-09-24 143415](https://user-images.githubusercontent.com/56078689/134648791-e14063ee-d5d6-44e3-af98-c02471ef7613.png)

- How ?
  - Use **User Context** to get the `user` state from `Usercontext.js`. Refer `Cart.js` for better Understanding.
  - `user` Object has a property `cartitems` that holds the number of items currently present in cart. Use it as `user.cartitems`.

**Comment by AngelicHeaven** [comment]
Hello, I would like to work on this issue.

**Comment by Mrhb787** [comment]
Yes go for it !

**Comment by AngelicHeaven** [comment]
Thank you! I will let you know if I need more info, but I think your instructions are clear.

**Comment by AngelicHeaven** [comment]
Hey, so I changed the Cart in the SideNav to display the number of current items in the cart. So I solved this issue. 

But I discovered another thing I would like to work on.  I figured out there is bug when it comes to counting items in the cart. When we have one book in Cart and we click to add quantity of that book by 1 -> we should have 2 items in Cart (cartitems = 2), but Cart still displays 1 (cartitems = 1).  So I would like to solve that issue too. 
![image](https://user-images.githubusercontent.com/71653637/134822009-b78cc81b-500f-48b0-89ae-4e0970616fa4.png)

**Comment by Mrhb787** [comment]
- Send PR for #80 issue separately.

- There is already an Issue related to this which is #49 You Can work On this. I have also Updated the issue as you told.

**Comment by AngelicHeaven** [comment]
Alright, I will send PR for the issue "Display of items count in cart in SideNav" separately.

**Comment by Mrhb787** [comment]
@AngelicHeaven Are You Still Working On this Issue ? 
- Please Respond otherwise I have to remove you from assignees so that other people can take up this issue.

**Comment by AngelicHeaven** [comment]
@Mrhb787  yes, I will pull PR for this by this friday.

**Comment by Mrhb787** [comment]
> @Mrhb787 I still haven't resolved the issue though. So I tried to make manual PR from git website for this issue.

It's ok If you don't get to solving the issue. I will look into it.

**Comment by RohitKumar-200** [comment]
@AngelicHeaven Any updates?
