### ISSUE TITLE
Missing seller public profile

### ISSUE THREAD

**Issue by RohitKumar-200** [Bookshlf-in/Website#94]
There is no component for seller public profile (route = /SellerProfile/<sellerId>). This route can be assessed by clicking on the seller's name in the book details section.

This component should have the following fields:
* Name
* Intro
* Photo
* No. of books sold
* Rating
* No. of ratings
* No. of reviews
* Verified batch if the seller is verified

All this info will be available in folloiwing backend API: /getSellerProfile?sellerId=<sellerId>
You can use "60f09b1a3a24d10022919697" as seller Id for demo purpose.

You can have your own design for this component or keep it like the design which is present in your own profile.

**Comment by Neniya** [comment]
I haven't done a lot, just tried to get data: 

```
import React, { useEffect } from "react";
import { useParams } from "react-router-dom";
import axios from "../../axios";

const SellerProfile = (props) => {
  const params = useParams();
  const sellerId = params.sellerId;

  useEffect(() => {
    const fetchData = async () => {
      const url = `/getSellerProfile?sellerId=${sellerId}`;
      axios.get(url).then((response) => {
        console.log(response);
      });
    };
    fetchData();
  }, []);

  return <div>{sellerId}</div>;
};

export default SellerProfile;

```

And I get an error:
<img width="681" alt="Screenshot 2021-10-12 at 12 25 06" src="https://user-images.githubusercontent.com/65239393/136939245-8a7a263c-25e6-4714-a395-afd84ec335cd.png">

The full url is  https://bookshlf.herokuapp.com/getSellerProfile?sellerId=60f09b1a3a24d10022919697 
If I write the url to address bar in browser it returns the data:

`{"name":"Awesome Sellers","intro":"Mai purani books bechta hu lekin wo ek dum nayi dikhti hai, kyuki mai unhe kabhi padta nahi.","photo":"https://firebasestorage.googleapis.com/v0/b/bookshlf.appspot.com/o/profile%2FZQ_usMsHUamyAvatar.png?alt=media&token=7d762a99-4d34-4abd-8eb1-6d2375b6e94f","noOfBooksSold":5,"rating":4,"noOfRatings":2,"noOfReviews":2,"isVerified":true,"_id":"60f09b1a3a24d10022919697","createdAt":"2021-07-15T20:31:22.480Z","updatedAt":"2021-09-29T09:26:38.260Z"}`


But request still doesn't work from the code. Am I doing something wrong?

**Comment by Neniya** [comment]
@Mrhb787 thank you for your answer. I do the same things but response from the server is error 500.
If it work for you correctly, I assume that this is a problem in my side. I'll try to find it.

**Comment by RohitKumar-200** [comment]
@Neniya This API doesn't require a login, and hence role of the user will not affect this api in any case.

**Comment by RohitKumar-200** [comment]
@Neniya 
One thing which you can do is:
Make a temporary PR with whatever code you have written. We will review your code in PR and help you resolve this issue.

**Comment by Neniya** [comment]
@Mrhb787 @RohitKumar-200 
I put the code here: **git@github.com:Neniya/Website.git** on the branch **seller-public-profile**
The route **SellerProfile/${sellerId}** can be accessed by clicking on the seller's name in the book details section
<img width="474" alt="Screenshot 2021-10-13 at 08 44 57" src="https://user-images.githubusercontent.com/65239393/137083802-ccf87abb-2e7b-44fc-8e0f-a28507b2c023.png">

**Comment by Neniya** [comment]
@Mrhb787 I did it, could you please review it?
